logs:
  url: https://home.mayeur.be:5123/log
  username: Cambristi Sushi RPI
  tag: wixtogoogle
  ndays: 30

cambristi:
  members_endpoint: https://www.cambristi.com/_functions/members/
  orders_endpoint: https://www.cambristi.com/_functions/orders/
  activities_endpoint: https://www.cambristi.com/_functions/activities/

geomap:
  index: /app/data/geomap.html

