logs:
#  url: https://cloud.cambristi.com:5123/log
#  username: Cambristi Sushi RPI
#  tag: wixtogoogle
  ndays: 15

cambristi:
  members_endpoint: https://www.cambristi.com/_functions/members/
  orders_endpoint: https://www.cambristi.com/_functions/orders/
  activities_endpoint: https://www.cambristi.com/_functions/activities/
  groups_endpoint: https://www.cambristi.com/_functions/groups/
  participants_endpoint: https://www.cambristi.com/_functions/participants/
  config_endpoint: https://www.cambristi.com/_functions/cloudconfig/
  secrets_endpoint: https://www.cambristi.com/_functions/secrets/

geomap:
  index: /app/data/geomap.html

google:
  max_tries: 3