services:
  wixgoogle:
    image: xmayeur/wixgooglesheet
    container_name: wixgoogle
    restart: always
    volumes:
      - /etc/vault:/root/.config/.vault
      - /root/.ssl:/root/.ssl
    dns:
      - 8.8.8.8
    healthcheck:
      test: "  $(curl -s -k  https://vault:8200/v1/sys/seal-status | jq '.sealed') = true ] || exit 0 "
      interval: 5s
      retries: 5
      start_period: 30s
      timeout: 10s