services:
  wixgooglesheet:
    image: xmayeur/wixgooglesheet
    container_name: wixgooglesheet
    restart: always
    volumes:
      - /root/.config/.vault:/root/.config/.vault
      - /root/.ssl:/root/.ssl
      - /app/geomap.html:/var/www/html/cambristi_members/geomap.html
    extra_hosts:
      - "vault:192.168.129.5"